### ISSUE TITLE
【bad style】google logo repeat

### ISSUE THREAD

**Issue by XfLoops** [xiongwilee/baidu2google#1]
![googlelogo](http://d.pcs.baidu.com/thumbnail/a48a0dd2b6678a2679f7b32d3981ab3a?fid=3675581816-250528-485578587981418&time=1453183200&rt=sh&sign=FDTAER-DCb740ccc5511e5e8fedcff06b081203-K61JW805%2F2uYR8KKbQfJQjgkCcE%3D&expires=2h&chkv=0&chkbd=0&chkpc=&dp-logid=2719691524&dp-callid=0&size=c850_u580&quality=100)

**Comment by xiongwilee** [comment]
@XfLoops 图片403了

**Comment by XfLoops** [comment]
@xiongwilee 奇怪奇怪了。我重新链接了一下，应该可以了。:sweat_smile: 这张图是我在mac上看的时候出现的问题。:eyes:

**Comment by xiongwilee** [comment]
这个是在已登录状态下（百度内部称：新首页）的页面，现在已经修复了；现在只对没有登录情况下的百度首页有影响

**Comment by xiongwilee** [comment]
晚上把已登录的页面和搜索结果页也给改掉 😂😂

**Comment by XfLoops** [comment]
:joy::joy::joy:
